<?php
/**
 * Magiccart 
 * @category 	Magiccart 
 * @copyright 	Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license 	http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2016-01-08 22:57:12
 * @@Modify Date: 2016-10-22 09:43:04
 * @@Function:
 */
 ?>
<?php if($this->getStatus() == 2) return; ?>
<?php $selector = 'alo-content-'.rand(0,999999999); ?>
<div class= "<?php echo $selector?> magicproduct megashop +autoplay">
<?php
$tabs = $this->getTabs();
$relatedTabs = $this->getRelatedTabs();
$numTabs = count($tabs);
$isAjax = $this->getAjax();

if($numTabs): ?>
    <span class="toggle-tab mobile" style="display:none"><i class="fa fa-bars"></i></span>
    <div class="block-title-tabs clearfix">
	    <?php echo '<h3 class="title">'.$this->getCatName().'</h3>';?>
	    <span class="toggle-tab mobile" style="display:none"><i class="fa fa-bars"></i></span>
		<ul class="magictabs toggle-content clearfix" data-ajax ='<?php echo $this->getAjaxCfg() ?>'>
		<?php $activated = $this->getTabActivated();
			$limit = $this->getLimit();
			$single = ($numTabs ==1) ? 'single' : '';
			foreach ($tabs as $type => $name):
				$status  = (!$isAjax || $activated ==$type) ? 'loaded' : '';
				$status .= ($type == $activated) ? " activated $single" : '';
				echo '<li class="item '.$status.'" data-type ="'.$type.'"><span class ="title">'.__($name).'</span></li>';
			endforeach;
			foreach ($relatedTabs as $cat):
				echo $isAjax ? '<li class="item cat" data-type ="'.$cat->getEntityId().'"><span class ="title">'.$cat->getName().'</span></li>' : '<li class="item cat" data-type ="'.$cat->getEntityId().'"><a href="'.$cat->getUrl().'"><span class ="title">'.$cat->getName().'</span></a></li>';
			endforeach;
		?>
		</ul>
    </div>
<?php endif ?>
	<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($this->getIdentifier())->toHtml();?>
	<div class="ajax_loading" style="display:none" data-url="<?php echo $this->getUrl('magicproduct/index/catalog', array('_type' => 'direct_link'))?>"></div>
	
	<div class="product-featured clearfix">
	    <div class="row">
			<div class="col-md-12 col-sm-12 col-right-tab">
			    <div class="product-featured-content">
					<div class="content-products" 
					<?php foreach ($this->getFrontendCfg() as $opt) :?>
						data-<?php echo $opt ?>='<?php echo $this->getData($opt) ?>'
					<?php endforeach;?>        
					>
					<?php 
						$timer = $this->getTimer();
						if($timer) echo $this->getContent('catalog/gridtimer.phtml');	
						else echo $this->getContent('catalog/grid.phtml');	
					?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	require([
		'jquery',
		'magiccart/slick',
		'magicproduct'
		], function($, slick, magicproduct){
			$(".<?php echo $selector?>").magicproduct({
				selector : ".<?php echo $selector?>", // Selector product grid
			});
		});
</script>

