<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
?>
<?php 
 $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
 $customerSession = $objectManager->get('Magento\Customer\Model\SessionFactory')->create();
?>
<link href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i&subset=latin-ext" rel="stylesheet"> 
<header class="page-header alothemes">
    <div class="header">
    	<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header-offer')->toHtml();?>
		<div class="header-top">
			<div class="container">
				<div class="row">
					<div class="mobile-center top-left col-md-4 col-sm-12 col-xs-12">
						<div class="welcometop"><?php echo $this->getChildHtml('welcometop'); ?></div>
						<div class="top-links">
							<?php echo $this->getChildHtml('account.links'); ?>
						</div>
					</div>
				    <div class="top-right mobile-center col-md-8 col-sm-12 col-xs-12">
				       <div class="header-top-link">
							<?php echo $this->getChildHtml('header.customlinks'); ?>
							<?php echo $this->getChildHtml('currency'); ?>
							<?php echo $this->getChildHtml('store_language'); ?>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="header-content menu-mobile">
			<div class="container">
				<div class="row">
				    <div class="content-logo col-md-3 col-sm-12 col-xs-12">
						<div class="header-logo">
							<?php echo $this->getChildHtml('logo'); ?>
						</div>
					</div>
					<div class="col-sm-12 visible-md-on">
						<?php echo $this->getChildHtml('navigation.sections'); ?>
					</div>
					<div class="content-cart">
						<div class="tool-header">
				        <div class="header-setting tool-setting">
							<div class="settting-switcher">
							    <div class="dropdown-toggle toggle-tab outside-close">
							    	<div class="text-setting text-bold"><?php echo $this->getChildHtml('account.links'); ?></div>
									<div class="text-setting text-hidden">
										<?php 
											if($customerSession->isLoggedIn()) {
												echo sprintf(__('Hello %s!'), $customerSession->getCustomer()->getFirstname());
											} else {
												echo __('Hello Guest!'); 
											}
										?>
									</div>
								</div>
							</div>
						</div>
						<?php echo $this->getChildHtml('minicart'); ?>
						<span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="header-bottom">
		    <div class="header-sticker">
		        <div class="container">
					<div class="header-right-menu">
						<div class="row">
							<div class="vertical-menu col-md-3 menu-mobile-none hidden-xs hidden-sm">
								<?php echo $this->getChildHtml('vmenu') ?>
							</div>
							<div class="content-search tool-topsearch alo-toggle toggle-tab-mobile col-sm-6 col-md-6">
								<div class="search-area">
									<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('social')->toHtml();?>
									<?php echo $this->getChildHtml('top.search'); ?>
								</div>
							</div>
							<div class="col-md-3 col-sm-6 free-shipping">
								<p class="ship-order"><?php echo __('Free Shipping On Order $99+') ?></p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</header>
